import harmonic_subharmonic_superharmonic_functions_higher_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace harmonic_subharmonic_superharmonic_functions_higher_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end harmonic_subharmonic_superharmonic_functions_higher_theorem_canonical_lane_mathlib
end HautevilleHouse
